### ISSUE TITLE
get GPS signal after standby mode

### ISSUE THREAD

**Issue by ptkuo0322** [stm32duino/X-NUCLEO-GNSS1A1#16]
I am working on the GPS project and using the GNSS1A1 expansion board as my GPS. However, it order to reach better power consumption, I want to turn GPS into standby mode/ periodic mode and to turn it back to normal more when needed.

For standby mode, I can turn it into standby mode. However, I can not wake it up and receive GPS signal anymore
Here is my code

```cpp
if (ppsTriggered)
   {
      ppsTriggered = false;
      ledState = !ledState;
      digitalWrite(LED_BUILTIN, ledState);

      // Output GPS information from previous second
      
     
      console.print("Valid fix: ");
      console.println(nmea.isValid() ? "yes" : "no");

      console.print("Nav. system: ");
      if (nmea.getNavSystem())
         console.println(nmea.getNavSystem());
      else
         console.println("none");

      console.print("Num. satellites: ");
      console.println(nmea.getNumSatellites());

      console.print("HDOP: ");
      console.println(nmea.getHDOP()/10., 1);
      
      long latitude_mdeg = nmea.getLatitude();
      long longitude_mdeg = nmea.getLongitude();
      console.print("Latitude (deg): ");
      console.println(latitude_mdeg / 1000000., 6);

      console.print("Longitude (deg): ");
      console.println(longitude_mdeg / 1000000., 6);

      nmea.clear();
   }

   //While the message isn't complete
   while (!ppsTriggered && gps.available())
   {
      //Fetch the character one by one
      char c = gps.read();
      console.print(c);
      //Pass the character to the library
      nmea.process(c);
   }
     MicroNMEA::sendSentence(gps,"$PSTMFORCESTANDBY,00010");
     delay(5000);
     digitalWrite(13, HIGH);
     delay(2000);
     digitalWrite(13,LOW);
     delay(10000);
```

Secondly, I tried to use power save mode(periodic mode)
I use the following code, but make no difference
```Cpp
if (ppsTriggered)
   {
      ppsTriggered = false;
      ledState = !ledState;
      digitalWrite(LED_BUILTIN, ledState);

      // Output GPS information from previous second
      
     
      console.print("Valid fix: ");
      console.println(nmea.isValid() ? "yes" : "no");

      console.print("Nav. system: ");
      if (nmea.getNavSystem())
         console.println(nmea.getNavSystem());
      else
         console.println("none");

      console.print("Num. satellites: ");
      console.println(nmea.getNumSatellites());

      console.print("HDOP: ");
      console.println(nmea.getHDOP()/10., 1);
      
      long latitude_mdeg = nmea.getLatitude();
      long longitude_mdeg = nmea.getLongitude();
      console.print("Latitude (deg): ");
      console.println(latitude_mdeg / 1000000., 6);

      console.print("Longitude (deg): ");
      console.println(longitude_mdeg / 1000000., 6);

      nmea.clear();
   }

   //While the message isn't complete
   while (!ppsTriggered && gps.available())
   {
      //Fetch the character one by one
      char c = gps.read();
      console.print(c);
      //Pass the character to the library
      nmea.process(c);
   }
     Serial.println("@ LEAST 10 TICKS!");
     MicroNMEA::sendSentence(gps, "$PSTMLOWPOWERONOFF,1,0,0,0,0,0,0,3,100,0,1,1,15,180");
     MicroNMEA::sendSentence(gps, "$PSTMSRR");

     delay(5000);
```

Can anyone give me a hint to let me know how to turn it to power save mode. Thanks

**Comment by cparata** [comment]
Hi @ptkuo0322 ,
I tried the standby command on my side at the end of the "if (ppsTriggered)" block as last command of the if and in this way it seems working fine on my side. I guess that the issue that you are experiencing is due to the position where you call the standby command; if you call it in a bad position it is possible that the parser of the MicroNMEA library does not work properly. Another possibility is to try to clear the buffer of the MicroNMEA library before calling the standby command if there is an API for that (maybe nmea.clear()?).  Let me know if in this way it works also on your side.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @ptkuo0322 ,
for example here you can find how I rewrote the "if (ppsTriggered)" block:

```C++
//If a message is recieved print all the informations
   if (ppsTriggered)
   {
      ppsTriggered = false;
      ledState = !ledState;
      digitalWrite(LED_BUILTIN, ledState);

      // Output GPS information from previous second
      console.print("Valid fix: ");
      console.println(nmea.isValid() ? "yes" : "no");

      console.print("Nav. system: ");
      if (nmea.getNavSystem())
         console.println(nmea.getNavSystem());
      else
         console.println("none");

      console.print("Num. satellites: ");
      console.println(nmea.getNumSatellites());

      console.print("HDOP: ");
      console.println(nmea.getHDOP()/10., 1);

      console.print("Date/time: ");
      console.print(nmea.getYear());
      console.print('-');
      console.print(int(nmea.getMonth()));
      console.print('-');
      console.print(int(nmea.getDay()));
      console.print('T');
      console.print(int(nmea.getHour()));
      console.print(':');
      console.print(int(nmea.getMinute()));
      console.print(':');
      console.println(int(nmea.getSecond()));

      long latitude_mdeg = nmea.getLatitude();
      long longitude_mdeg = nmea.getLongitude();
      console.print("Latitude (deg): ");
      console.println(latitude_mdeg / 1000000., 6);

      console.print("Longitude (deg): ");
      console.println(longitude_mdeg / 1000000., 6);

      long alt;
      console.print("Altitude (m): ");
      if (nmea.getAltitude(alt))
         console.println(alt / 1000., 3);
      else
         console.println("not available");

      console.print("Speed: ");
      console.println(nmea.getSpeed() / 1000., 3);
      console.print("Course: ");
      console.println(nmea.getCourse() / 1000., 3);

      console.println("-----------------------");
      if(nmea.isValid())
      {
        nmea.clear();
        MicroNMEA::sendSentence(gps,"$PSTMFORCESTANDBY,00010");
      }else
      {
        nmea.clear();
      }
   }

```

Basically, I wait for the sync of the satellites, then when I get the sync I send the GPS module in standby and then, when it wakes up , it waits for the next sync and then goes again in standby and so on.
This sequence seems working fine on my side.
Best Regards,
Carlo

**Comment by cparata** [comment]
I only noticed that sometimes the module takes a while to process the Standby event and it does not act immediately but as soon as the module process the standby command, then  it goes to standby and then restart after the delay set into the command.

**Comment by ptkuo0322** [comment]
> Hi @ptkuo0322 ,
> for example here you can find how I rewrote the "if (ppsTriggered)" block:
> 
> ```c++
> //If a message is recieved print all the informations
>    if (ppsTriggered)
>    {
>       ppsTriggered = false;
>       ledState = !ledState;
>       digitalWrite(LED_BUILTIN, ledState);
> 
>       // Output GPS information from previous second
>       console.print("Valid fix: ");
>       console.println(nmea.isValid() ? "yes" : "no");
> 
>       console.print("Nav. system: ");
>       if (nmea.getNavSystem())
>          console.println(nmea.getNavSystem());
>       else
>          console.println("none");
> 
>       console.print("Num. satellites: ");
>       console.println(nmea.getNumSatellites());
> 
>       console.print("HDOP: ");
>       console.println(nmea.getHDOP()/10., 1);
> 
>       console.print("Date/time: ");
>       console.print(nmea.getYear());
>       console.print('-');
>       console.print(int(nmea.getMonth()));
>       console.print('-');
>       console.print(int(nmea.getDay()));
>       console.print('T');
>       console.print(int(nmea.getHour()));
>       console.print(':');
>       console.print(int(nmea.getMinute()));
>       console.print(':');
>       console.println(int(nmea.getSecond()));
> 
>       long latitude_mdeg = nmea.getLatitude();
>       long longitude_mdeg = nmea.getLongitude();
>       console.print("Latitude (deg): ");
>       console.println(latitude_mdeg / 1000000., 6);
> 
>       console.print("Longitude (deg): ");
>       console.println(longitude_mdeg / 1000000., 6);
> 
>       long alt;
>       console.print("Altitude (m): ");
>       if (nmea.getAltitude(alt))
>          console.println(alt / 1000., 3);
>       else
>          console.println("not available");
> 
>       console.print("Speed: ");
>       console.println(nmea.getSpeed() / 1000., 3);
>       console.print("Course: ");
>       console.println(nmea.getCourse() / 1000., 3);
> 
>       console.println("-----------------------");
>       if(nmea.isValid())
>       {
>         nmea.clear();
>         MicroNMEA::sendSentence(gps,"$PSTMFORCESTANDBY,00010");
>       }else
>       {
>         nmea.clear();
>       }
>    }
> ```
> 
> Basically, I wait for the sync of the satellites, then when I get the sync I send the GPS module in standby and then, when it wakes up , it waits for the next sync and then goes again in standby and so on.
> This sequence seems working fine on my side.
> Best Regards,
> Carlo

Thank you for your reply. I try to test your code, and it does not work well for me. From my result, the GPS may go into standby mode randomly even if the nmea.isValid() is not correct.  I am still trying.

Also, I ask questions in the ST community. One of the ST employee tells me that if we turn the GPS into standby mode, the only way to wake it up is to use Hardware way  pin to do it. And I am working on  customized PCB, I still can not test about it since my new version PCB. If I find the way, I will reply.

Again, thank for your suggestion!

**Comment by fpistm** [comment]
Hi @ptkuo0322 
any update on this ?
Thanks

**Comment by fpistm** [comment]
@cparata are you ok to close it if there is no issue inside the library?

**Comment by cparata** [comment]
Yes, we can close it
