### ISSUE TITLE
I can't read gps data using uarts

### ISSUE THREAD

**Issue by ChevalierLouis** [stm32duino/X-NUCLEO-GNSS1A1#17]
hello, I am using an arduino uno with the X-NUCLEO-GNSS1A1 
I have cérate a software serial conection using SoftwareSerial.h in the arduino IDE 

this is my code :

    #include <SoftwareSerial.h>                        
    #define RX 8 
    #define TX 2 
    SoftwareSerial GPS(RX, TX); 
    byte data; 
    
    void setup()
    // Initialisations
    {
      Serial.begin(9600); 
      GPS.begin(9600);    
    }
    
    void loop()
  
      {
       if (GPS.available() > 0 )  {
        data= GPS.read();  
        Serial.write(data);
        }
    }

J15: closed
J14: closed
J13: closed
J12: closed
J11: closed
J10: open
J9: closed
J8: open
J7: open 

J5: closed
J4: closed
J3: closed
J2: open 

I tried inside and outside
do i really need to put the button battery in?

Have a nice day 
Louis,

**Comment by cparata** [comment]
Hi @ChevalierLouis ,
unfortunately, I think that Arduino UNO does not have enough memory to run this library. In fact, "avr" platform is not officially supported by the library. I suggest to use a more powerful board like Nucleo-F401RE or Arduino DUE.
Best Regards,
Carlo

**Comment by ChevalierLouis** [comment]
Thanks for the quick response, my code looks good? I will try with an esp8266 and an esp32

**Comment by cparata** [comment]
I suggest to start from the sample applications that you can find in the library. You can use I2C, if you don't have a UART peripheral available in your target platform. I'm sorry, but I don't know SoftwareSerial library.
Best Regards,
Carlo

**Comment by ChevalierLouis** [comment]
Thanks for the help I will try it
